- name: Sync dotfiles
  shell: "stow . --target {{ ansible_env.HOME }} --verbose=2 --adopt"
  args:
      chdir: "{{ playbook_dir }}/../dotfiles"
  register: res
  changed_when: 'res.stderr is search("LINK: ")'

